"""Markdown output generation utilities.

Extracted from the Notebook_GEMINI.ipynb batch processing cell.
"""

from datetime import datetime


def generate_markdown_output(
    country: str,
    risk_title: str,
    risk_type: list,
    previous_scores: tuple,
    update_period: tuple,
    paragraph_1: str,
    paragraph_2: str,
    status_recommendation: dict,
    citations: list,
    warnings: list,
    run_id: str
) -> str:
    """Generate markdown content for a single risk output."""

    # Status recommendation section
    if status_recommendation:
        status_change = status_recommendation.get("status_change", "N/A")
        rationale = status_recommendation.get("rationale", "N/A")

        current = status_recommendation.get("current_seriousness", {})
        current_l = current.get("likelihood", "N/A") if current else "N/A"
        current_i = current.get("impact", "N/A") if current else "N/A"

        status_section = f"""## Status Recommendation

**Recommended Status Change:** {status_change}

| Metric | Previous | Current |
|--------|----------|---------|
| Likelihood | {previous_scores[0]} | {current_l} |
| Impact | {previous_scores[1]} | {current_i} |

**Rationale:** {rationale}
"""
    else:
        status_section = "## Status Recommendation\n\n*Not generated*\n"

    # Citations section
    if citations:
        citations_lines = ["## Citations\n"]
        for i, cit in enumerate(citations, 1):
            title = cit.get("title", "Untitled")
            url = cit.get("url", "#")
            reliability = cit.get("reliability", 0)
            citations_lines.append(f"{i}. [{title}]({url}) (Reliability: {reliability:.2f})")
        citations_section = "\n".join(citations_lines)
    else:
        citations_section = "## Citations\n\n*No citations generated*"

    # Warnings section
    if warnings:
        warnings_section = "## Processing Warnings\n\n" + "\n".join(f"- {w}" for w in warnings)
    else:
        warnings_section = ""

    # Full markdown
    md = f"""# Active Warning Update: {country}

**Risk Title:** {risk_title}

**Risk Type:** {", ".join(risk_type)}

**Update Period:** {update_period[0]} to {update_period[1]}

**Run ID:** `{run_id}`

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Narrative Update

{paragraph_1 or "*Paragraph 1 not generated*"}

{paragraph_2 or "*Paragraph 2 not generated*"}

---

{status_section}

---

{citations_section}

{warnings_section}

---

*Generated by Active Warnings Agent*
"""
    return md


def generate_summary_markdown(results: list, start_date: str, end_date: str) -> str:
    """Generate summary markdown for the batch run."""

    success = [r for r in results if r["status"] == "SUCCESS"]
    failed = [r for r in results if r["status"] == "FAILED"]

    # Recommendation breakdown
    rec_counts = {}
    for r in success:
        rec = r.get("recommendation", "N/A")
        rec_counts[rec] = rec_counts.get(rec, 0) + 1

    rec_table = "\n".join(f"| {k} | {v} |" for k, v in sorted(rec_counts.items()))

    md = f"""# Active Warnings Batch Processing Summary

**Run Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

**Update Period:** {start_date} to {end_date}

## Results Overview

| Metric | Count |
|--------|-------|
| Total Risks | {len(results)} |
| Successful | {len(success)} |
| Failed | {len(failed)} |

## Status Recommendations Breakdown

| Recommendation | Count |
|----------------|-------|
{rec_table}

## Successful Runs

| # | Country | Recommendation | File |
|---|---------|----------------|------|
"""

    for r in success:
        md += f"| {r['index']} | {r['country']} | {r.get('recommendation', 'N/A')} | {r['file']} |\n"

    if failed:
        md += "\n## Failed Runs\n\n| # | Country | Error |\n|---|---------|-------|\n"
        for r in failed:
            md += f"| {r['index']} | {r['country']} | {r.get('error', 'Unknown')[:50]}... |\n"

    md += "\n\n---\n*Generated by Active Warnings Batch Processor*"

    return md
